agent_address = "/run/spire/sockets/agent.sock"
cmd = "/usr/bin/sleep"
cmd_args = "3600"
cert_dir = "/run/spire/certs"
svid_file_name = "svid.pem"
svid_key_file_name = "svid_key.pem"
svid_bundle_file_name = "bundle.pem"
renew_signal = "SIGHUP"
add_intermediates_to_bundle = true
