apiVersion: v1
kind: ConfigMap
metadata:
  name: spire-server-oidc
data:
  oidc.conf: |
    health_checks {
        listener_enabled = true
        bind_port = "8008"
    }
    domain = "oidc-discovery.example.org"
    insecure_addr = ":8080"
    log_level = "INFO"
    server_socket_path = "/run/spire/server/private/api.sock"
