apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: spire
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: spire-server
        static_configs:
          - targets: ['spire-server:9988']
      - job_name: spire-agent
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names: [spire]
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_label_app]
            regex: spire-agent
            action: keep
