agent_address = "/run/spire/sockets/agent.sock"
cmd = "/usr/sbin/nginx"
cmd_args = "-g 'daemon off;'"
cert_dir = "/etc/spiffe/certs"
add_intermediates_to_bundle = true
svid_file_name = "svid.pem"
svid_key_file_name = "svid_key.pem"
svid_bundle_file_name = "bundle.pem"
renew_signal = "SIGHUP"
