server {
    bind_address = "0.0.0.0"
    bind_port = "8081"
    trust_domain = "example.org"
    data_dir = "/run/spire/data"
    log_level = "INFO"
    ca_ttl = "168h"
    default_x509_svid_ttl = "1h"
}

plugins {
    DataStore "sql" {
        plugin_data {
            database_type = "postgres"
            connection_string = "host=postgres port=5432 user=spire dbname=spire password=spire-pwd-change-me sslmode=disable"
        }
    }
    NodeAttestor "k8s_psat" {
        plugin_data {
            clusters = {
                "spire-demo" = {
                    service_account_allow_list = ["spire:spire-agent"]
                }
            }
        }
    }
    KeyManager "aws_kms" {
        plugin_data {
            region = "us-east-1"
            key_metadata_file = "/run/spire/data/kms_key_metadata"
        }
    }
}
